---
- name: Crear estructura de directorios
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /tmp/2do_parcial/alumno
    - /tmp/2do_parcial/equipo

- name: Generar datos_alumno.txt
  template:
    src: datos_alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: Generar datos_equipo.txt
  template:
    src: datos_equipo.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

- name: Configurar sudoers para grupo 2PSupervisores
  copy:
    dest: /etc/sudoers.d/2PSupervisores
    content: "%2PSupervisores ALL=(ALL) NOPASSWD: ALL\n"
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
